namespace: mahadzar81
name: adagios
version: 1.0.6
readme: README.md
authors:
- mahadzar.karsof@gmail.com
description: Ansible collection for Adagios
license:
- MIT
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/mahadzar81/ansible-collection-adagios
documentation: http://adagios.org/
homepage: https://github.com/mahadzar81/ansible-collection-adagios
issues: http:/https://github.com/mahadzar81/ansible-collection-adagios/issues
build_ignore: []

