---
namespace: mahadzar81
name: adagios
version: 1.0.11
readme: README.md
description: >
  Ansible collection to deploy Nagios Core 4.x and Adagios web UI,
  with full SELinux support for RHEL/Rocky Linux and idempotent task design.
authors:
  - Mahadzar
license:
  - MIT
tags:
  - monitoring
  - nagios
  - adagios
  - rhel
  - selinux
dependencies: {}
repository: https://github.com/mahadzar81/ansible-collection-adagios
documentation: http://adagios.org/
homepage: https://github.com/mahadzar81/ansible-collection-adagios
issues: https://github.com/mahadzar81/ansible-collection-adagios/issues
