---
- name: Load OS vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution | lower }}.yml"
    - "setup-{{ ansible_os_family | lower }}.yml"
    - "setup-unsupported.yml"

- name: Install MK Livestatus
  ansible.builtin.include_tasks: livestatus.yml

- name: Install PNP4Nagios
  ansible.builtin.include_tasks: pnp4nagios.yml

- name: Install Adagios
  ansible.builtin.include_tasks: install.yml

- name: Configure Adagios
  ansible.builtin.include_tasks: configure.yml

- name: Manage SELinux policy for Adagios
  ansible.builtin.include_tasks: selinux.yml
  when:
    - adagios_selinux_manage | bool
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"
