---
# Loaded automatically by include_vars on Debian family systems
_nagios_apache_service: apache2
_nagios_apache_conf_dir: /etc/apache2/conf-available
_nagios_apache_user: www-data
_nagios_shell: /usr/sbin/nologin
