# Package lists by OS family (overridden in tasks via include_vars)

_nagios_redhat_packages:
  - gcc
  - glibc
  - glibc-common
  - gd
  - gd-devel
  - make
  - wget
  - unzip
  - net-snmp
  - net-snmp-utils
  - openssl-devel
  - gettext
  - automake
  - autoconf
  - perl
  - httpd
  - php
  - php-cli
  - mod_fcgid
  - python3
  - python3-pip
  - python3-passlib
  - policycoreutils
  - policycoreutils-python-utils  # for semanage (RHEL8+)
  - setools-console
  - libselinux-utils
  - checkpolicy

_nagios_debian_packages:
  - autoconf
  - gcc
  - libc6
  - make
  - wget
  - unzip
  - apache2
  - php
  - libapache2-mod-php
  - libgd-dev
  - libssl-dev
  - gettext
  - automake
  - libperl-dev
  - python3
  - python3-pip
  - python3-passlib