---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Gather SELinux facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - selinux

  roles:
    - role: mahadzar81.adagios.nagios_core
    - role: mahadzar81.adagios.adagios
