---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: rocky9
    image: rockylinux/rockylinux:9
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    pre_build_image: true
    docker_networks:
      - name: molecule_net
    env:
      container: docker

  - name: rocky8
    image: rockylinux/rockylinux:8
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    pre_build_image: true
    docker_networks:
      - name: molecule_net

  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: true
    docker_networks:
      - name: molecule_net

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        nagiosadmin_pass: "Molecule_T3st_Pass!"
        nagios_selinux_manage: false   # Docker containers lack full SELinux
        adagios_selinux_manage: false
  options:
    vvv: false

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
