---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  # Test on Rocky Linux (RHEL equivalent)
  - name: nagios-rhel
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    # FIX: Force connection as root to bypass sudo password prompts
    user: root
    # Systemd capability requirements
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    command: "/usr/sbin/init"

  # Test on Ubuntu (Debian equivalent)
  - name: nagios-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    # Systemd capability requirements
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      remote_tmp: /tmp/ansible-tmp
#      stdout_callback: yaml
      # Increase timeout for source compilation
      # timeout: 60

verifier:
  name: ansible