---
- name: Restart nagios
  ansible.builtin.service:
    name: nagios
    state: restarted

- name: Restart apache
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: restarted

- name: Restart adagios wsgi
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
