---
galaxy_info:
  role_name: nagios_core
  author: mahadzar81
  description: "Compile and install Nagios Core 4.x from source with SELinux support"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

dependencies: []
